# Generated by Django 3.1.2 on 2021-05-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userdata',
            new_name='user',
        ),
    ]
