# Generated by Django 3.1.2 on 2021-05-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='style')),
                ('image2', models.ImageField(upload_to='base')),
                ('image3', models.ImageField(upload_to='generated')),
            ],
        ),
    ]
